apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sysctl-vm-max-map-count
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: sysctl-vm-max-map-count
  template:
    metadata:
      labels:
        name: sysctl-vm-max-map-count
    spec:
      hostPID: true
      containers:
        - name: sysctl
          image: busybox:1.35
          command: ["sh", "-c", "sysctl -w vm.max_map_count=9262144"]
          securityContext:
            privileged: true
      restartPolicy: Always
      tolerations:
        - operator: "Exists"
